// Holds values for actions


export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const LOGIN_SUCCESS = "LOGIN_SUCCESS"

export const GET_PROFILE = 'GET_PROFILE'

export const REMOVE_PROFILE = 'REMOVE_PROFILE'

export const SET_DB_PROFILE = 'SET_DB_PROFILE'

export const REMOVE_DB_PROFILE = 'REMOVE_DB_PROFILE'

export const FETCH_DB_POSTS_SUCCESS = 'FETCH_DB_POSTS_SUCCESS'

export const REMOVE_DB_POSTS = 'REMOVE_DB_POSTS'

export const FETCH_DB_POST_COMMENTS_SUCCESS = 'FETCH_DB_POST_COMMENTS_SUCCESS'

export const FETCH_DB_POST_COMMENTS_FAILURE = 'FETCH_DB_POST_COMMENTS_FAILURE'
